name: Test
on:
    pull_request:
        branches:
            - main
    push:
        paths:
            - src/**
            - test/**
            - package.json
            - vite.config.ts
            - vitest.config.ts
            - vitest.setup.ts
            - .github/workflows/**
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v3

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile
            - run: pnpm test
